[package]
name = "cui-web-app"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
    "HtmlElement",
    "MouseEvent",
    "WheelEvent",
    "DragEvent",
    "DataTransfer",
    "TouchEvent",
    "Touch",
    "TouchList",
    "console",
]}
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gloo = "0.10"
uuid = { version = "1.0", features = ["v4", "js"] }
typetag = "0.2"
